-- =============================================================================
-- MCA Placement DB Schema
-- Clean complete schema for fresh database initialization
-- =============================================================================

-- ── 1. Core Users Table ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "users" (
  "id"                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"                VARCHAR(255),
  "college_email_id"    VARCHAR(255) UNIQUE,
  "personal_email_id"   VARCHAR(255) UNIQUE,
  "phone_number"        VARCHAR(50),
  "aadhar"              VARCHAR(50),
  "linkedIn"            VARCHAR(255),
  "gitHub"              VARCHAR(255),
  "usn"                 VARCHAR(50),
  "google_id"           VARCHAR(255),
  "ug_cgpa"             DOUBLE PRECISION,
  "first_sem_sgpa"      DOUBLE PRECISION,
  "tenth_marks"         DOUBLE PRECISION,
  "twelfth_marks"       DOUBLE PRECISION,
  "resume_url"          TEXT,
  "profile_picture_url" TEXT,
  "verified"            BOOLEAN DEFAULT false,
  "unlock_requested"    BOOLEAN DEFAULT false,
  "placed"              BOOLEAN DEFAULT false,
  "gender"              VARCHAR(50),
  "created_at"          TIMESTAMP DEFAULT NOW()
);

-- ── 2. SPC Accounts Table ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "spc_accounts" (
  "id"           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id"      INT REFERENCES "users" ("id") ON DELETE CASCADE,
  "spc_username" VARCHAR(255) UNIQUE,
  "password"     VARCHAR(255)
);

-- ── 3. Companies Table ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "companies" (
  "id"              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"            VARCHAR(255),
  "min_cgpa"        DOUBLE PRECISION,
  "stipend"         VARCHAR(255),
  "package"         VARCHAR(255),
  "test_date"       DATE,
  "interview_date"  DATE,
  "deadline"        TIMESTAMP,
  "created_by"      INT REFERENCES "users" ("id") ON DELETE SET NULL,
  "status"          VARCHAR(50) DEFAULT 'ongoing',
  "consent_blocked" BOOLEAN DEFAULT false,
  "tracker_blocked" BOOLEAN DEFAULT false,
  "created_at"      TIMESTAMP DEFAULT NOW()
);

-- ── 4. Student Applications Table ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "applications" (
  "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" INT REFERENCES "users" ("id") ON DELETE CASCADE,
  "company_id" INT REFERENCES "companies" ("id") ON DELETE CASCADE,
  "consent"    BOOLEAN DEFAULT false,
  "tracker"    BOOLEAN DEFAULT false,
  CONSTRAINT "uq_applications" UNIQUE ("student_id", "company_id")
);

-- ── 5. Forms Table ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "forms" (
  "id"                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title"               VARCHAR(255),
  "type"                VARCHAR(50), -- e.g. placement, profile_data
  "company_id"          INT REFERENCES "companies" ("id") ON DELETE CASCADE,
  "created_by"          INT REFERENCES "users" ("id") ON DELETE SET NULL,
  "created_at"          TIMESTAMP DEFAULT NOW(),
  "accepting_responses" BOOLEAN DEFAULT true
);

-- ── 6. Form Questions Table ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "form_questions" (
  "id"            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question_text" TEXT NOT NULL,
  "field_type"    VARCHAR(50) NOT NULL -- text, number, file, etc.
);

-- ── 7. Form Question Map Table ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "form_question_map" (
  "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "form_id"     INT REFERENCES "forms" ("id") ON DELETE CASCADE,
  "question_id" INT REFERENCES "form_questions" ("id") ON DELETE CASCADE,
  "is_required" BOOLEAN DEFAULT true,
  CONSTRAINT "uq_form_question_map" UNIQUE ("form_id", "question_id")
);

-- ── 8. Form Responses Table ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "form_responses" (
  "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "form_id"     INT REFERENCES "forms" ("id") ON DELETE CASCADE,
  "student_id"  INT REFERENCES "users" ("id") ON DELETE CASCADE,
  "company_id"  INT REFERENCES "companies" ("id") ON DELETE CASCADE,
  "question_id" INT REFERENCES "form_questions" ("id") ON DELETE CASCADE,
  "answer"      TEXT,
  CONSTRAINT "uq_form_responses" UNIQUE ("form_id", "student_id", "question_id")
);

-- ── 9. Messages (Chat) Table ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "messages" (
  "id"              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender_id"       INT REFERENCES "users" ("id") ON DELETE CASCADE,
  "message_text"    TEXT,
  "attachment_url"  TEXT,
  "attachment_name" TEXT,
  "parent_id"       INT REFERENCES "messages" ("id") ON DELETE SET NULL,
  "created_at"      TIMESTAMP DEFAULT NOW(),
  "updated_at"      TIMESTAMP DEFAULT NOW()
);

-- ── 10. Mentions Table ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "mentions" (
  "id"                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "message_id"        INT REFERENCES "messages" ("id") ON DELETE CASCADE,
  "mentioned_user_id" INT REFERENCES "users" ("id") ON DELETE CASCADE,
  CONSTRAINT "uq_mention" UNIQUE ("message_id", "mentioned_user_id")
);

-- ── 11. Notification Subscriptions Table ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "notification_subscriptions" (
  "id"              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id"         INT REFERENCES "users" ("id") ON DELETE CASCADE,
  "endpoint"        TEXT NOT NULL UNIQUE,
  "subscription"    JSONB NOT NULL,
  "expiration_time" BIGINT,
  "created_at"      TIMESTAMP DEFAULT NOW(),
  "updated_at"      TIMESTAMP DEFAULT NOW()
);

-- ── Indexes for Optimization ─────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS "idx_messages_created_at"  ON "messages" ("created_at" DESC);
CREATE INDEX IF NOT EXISTS "idx_mentions_message_id"  ON "mentions" ("message_id");
CREATE INDEX IF NOT EXISTS "idx_notification_subscriptions_user_id" ON "notification_subscriptions" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_users_usn" ON "users" ("usn");
CREATE INDEX IF NOT EXISTS "idx_users_college_email" ON "users" ("college_email_id");
