CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "college_email_id" varchar UNIQUE,
  "personal_email_id" varchar UNIQUE,
  "phone_number" int[10],
  "aadhar" bigint,
  "linkedIn" varchar,
  "gitHub" varchar,
  "usn" varchar,
  "google_id" varchar,
  "ug_cgpa" float,
  "first_sem_sgpa" float,
  "tenth_marks" float,
  "twelfth_marks" float,
  "resume_url" text,
  "verified" boolean,
  "created_at" timestamp
);

CREATE TABLE "spc_accounts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "spc_username" varchar UNIQUE,
  "password" varchar
);

CREATE TABLE "companies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "min_cgpa" float,
  "stipend" varchar,
  "package" varchar,
  "test_date" date,
  "interview_date" date,
  "created_by" int,
  "created_at" timestamp
);

CREATE TABLE "applications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" int,
  "company_id" int,
  "consent" boolean,
  "tracker" boolean
);

CREATE TABLE "forms" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "type" varchar,
  "company_id" int,
  "created_by" int,
  "created_at" timestamp
);

CREATE TABLE "form_questions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question_text" varchar,
  "field_type" varchar
);

CREATE TABLE "form_question_map" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "form_id" int,
  "question_id" int,
  "is_required" boolean
);

CREATE TABLE "form_responses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "form_id" int,
  "student_id" int,
  "company_id" int,
  "question_id" int,
  "answer" text
);

ALTER TABLE "spc_accounts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "companies" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "applications" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "applications" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "forms" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "forms" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "form_question_map" ADD FOREIGN KEY ("form_id") REFERENCES "forms" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "form_question_map" ADD FOREIGN KEY ("question_id") REFERENCES "form_questions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "form_responses" ADD FOREIGN KEY ("form_id") REFERENCES "forms" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "form_responses" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "form_responses" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "form_responses" ADD FOREIGN KEY ("question_id") REFERENCES "form_questions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

